version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
      
  build:
    commands:
      - export FLASK_ENV=testing
      - set -e # exit on error
      - pytest tests/
      
  post_build:
    commands:
      # Save the Docker image as a tar file
      #- docker build -t compumundo-black-list-ci-container-image .
      #- docker save compumundo-black-list-ci-container-image:latest -o docker-image.tar
      #- gzip docker-image.tar
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then
          echo "Build succeeded, running post-build steps"
          touch text.txt
        else
          echo "Build failed, skipping post-build steps"
          exit 1
        fi

artifacts:
  files:
    #- docker-image.tar.gz
    - text.txt
  name: docker-image-$(date +%Y-%m-%d_%H-%M)
