version: 0.2

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - pip install -r requirements.txt
      
  build:
      on-failure: ABORT
      commands:
        - export FLASK_ENV=testing
      - set -e # exit on error
      - pytest tests/
      
  post_build:
    on-failure: ABORT
    commands:
      # Save the Docker image as a tar file
      #- docker build -t compumundo-black-list-ci-container-image .
      #- docker save compumundo-black-list-ci-container-image:latest -o docker-image.tar
      #- gzip docker-image.tar
      - touch text.txt

artifacts:
  files:
    #- docker-image.tar.gz
    - text.txt
  name: docker-image-$(date +%Y-%m-%d_%H-%M)
