version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
      - touch text.txt
  build:
    commands:
      - export FLASK_ENV=testing
      - pytest tests/
      - docker build -t compumundo-black-list-ci-container-image .
artifacts:
  files:
    - 'compumundo-black-list-ci-container-image'
